# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skeema < Formula
  desc "Skeema is a tool for managing MySQL tables and schema changes in a declarative fashion using pure SQL."
  homepage "https://www.skeema.io/"
  version "1.11.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skeema/skeema/releases/download/v1.11.0/skeema_1.11.0_mac_amd64.tar.gz"
      sha256 "1912b12616d06b91a2098b27730dcd11f0be68e39bf56d10f5e243e60531241e"

      def install
        bin.install "skeema"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skeema/skeema/releases/download/v1.11.0/skeema_1.11.0_mac_arm64.tar.gz"
      sha256 "634dfe30e9ae2a0d78b2a147d9cc80534d59116c6c16764f805998e6167da403"

      def install
        bin.install "skeema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/skeema/skeema/releases/download/v1.11.0/skeema_1.11.0_linux_amd64.tar.gz"
      sha256 "cdf5526732640ea469c95afb8650c224b0270f9361b9e2086a4f860964f35e54"

      def install
        bin.install "skeema"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skeema/skeema/releases/download/v1.11.0/skeema_1.11.0_linux_arm64.tar.gz"
      sha256 "7ded3b8810a02a228b4952f600e6c58960dbfa9ccc4bd34e6729604bc4d91f33"

      def install
        bin.install "skeema"
      end
    end
  end
end
